### ISSUE TITLE
Multiple streamlit books under one app

### ISSUE THREAD

**Issue by Spiruel** [sebastiandres/streamlit_book#1]
Hi,

Thanks for making this really useful library!

I am currently using it in a streamlit app, where there are multiple pages and each of them point to a different streamlit book.

I would like each book to have page numbers unique to each book, but unfortunately they are currently shared across the app. The page number is defined using ` st.session_state.file_number` .

Is it possible to change this so that file_number is tracked in the session state, but with a unique id perhaps defined under `stb.set_book_config`?

**Comment by sebastiandres** [comment]
Wow, that's such a nice concept. I imagine it could be done, let's brainstorm it! 
What would be a good convention to call them? How would you like it to look and do from the user perspective?

I would greatly appreciate if share your apps so I can take a look and better understand the request.

And thanks, it's great to know the library is being used!

**Comment by Spiruel** [comment]
Great! As a quick workaround for my own prototyping, I passed a `book_id` argument into `set_page_config`. `st.session_state.file_number` was then initialised as a dictionary with book_id's as the key. You can see multiple streamlit books working properly under the same app here: https://share.streamlit.io/spiruel/satschool/main/app.py

An argument such as `book_id` could make this feature work as needed. Maybe `book_id` should automatically be generated from the starting file, so that multiple books working in the same streamlit app is the intended default behaviour? Then you could still explicitly pass a `book_id` if you wanted multiple pages to share the same page number for whatever reason.

**Comment by sebastiandres** [comment]
Hey, sorry for the waiting. Busy couple of weeks, but I have kept thinking into this. 
I took a look at your solution, and that should work, but I want to take a completely different approach. 

I have learn recently that the api has functions to handle query parameters, so we could use that to navigate updating the url (without effort for the user) and allowing to share a specific page of the book. I'll include a book_id so we can have multiple books, if needed.  

Example:
http://localhost:8501/?book_id=my_first_book&page=42
http://localhost:8501/?book_id=my_first_book&page=1
http://localhost:8501/?book_id=my_other_book&page=1

I think it solves the issue at hand and provides a cool new feature! Jumping into a specific page is a must for any book lover!

I'll do my best to close this issue this week!

References:
https://docs.streamlit.io/library/api-reference/utilities/st.experimental_get_query_params
https://docs.streamlit.io/0.83.0/library/api-reference/utilities/st.experimental_set_query_params

**Comment by sebastiandres** [comment]
Couldn't make it work with query_params as I needed, but I have a working version.
Upgrade to 0.5.3 and you should be able to use book_number as a parameters. 
For convenience, I made a wrapper for several books. It's all on the docs: https://streamlit-book.readthedocs.io/en/latest/configuration.html

And a working example should look as in https://github.com/sebastiandres/streamlit_book/blob/main/multi_book.py

Let me know if it works/ you find additional issues!

**Comment by sebastiandres** [comment]
Just to let you know that I had a huge rewritting of the code, and some conventions might have changed:

Check out the interactive examples!!!
Simple activities: https://share.streamlit.io/sebastiandres/stb_activities_demo_v070/main
Traditional pagination: https://share.streamlit.io/sebastiandres/stb_chapter_demo_v070/main
The new book format: https://share.streamlit.io/sebastiandres/stb_book_demo_v070/main

And also a HUGE update to the docs: https://streamlit-book.readthedocs.io

**Comment by Spiruel** [comment]
I saw your tweet about this - looks fantastic! Thank you very much, I shall be trying this all out today
