### ISSUE TITLE
How to save the option chosen by the user as a df?

### ISSUE THREAD

**Issue by martinagalletti** [sebastiandres/streamlit_book#2]
Hi ! your library is great ! I was wondering whether there was an option to save to a df the correct answer and the answer selected by the user! Thanks a lot!

**Comment by sebastiandres** [comment]
Hi Martina! Thank you! It's always surprising seeing people using this library! 
Yes, it could be done, but there are several things to consider:
- Link the answers to a specific user (login? provide name?) or store anonymously for several users?
- How to handle iterations/changes on the book.  I think answers should be linked to the commit version, so you preserve old answers but can evolve the book if needed.
- Where and how to store it? A plain and boring csv file or a db? Store in json? Store the question and answer number, or the whole question/answer (to decouple from the files and versioning).

What would make more sense in your particular user case?

**Comment by martinagalletti** [comment]
Thanks for your quick answer ! 
To answer your questions :  
- I would need to link the answers to a specific username 
- Answers linked to the commit version 
- Store the question + answer given + correct answer in json. The whole q/a would be better but also number is fine for my use case!

**Comment by sebastiandres** [comment]
Hi Martina! I have a working version for this, I'll work on a proper documentation to have the new version on pypi this week.

**Comment by sebastiandres** [comment]
OK, here's a public demo with the latest version on github (not yet on pypi): https://share.streamlit.io/sebastiandres/stb_demo_v070/main

**Comment by martinagalletti** [comment]
Hi Sebastian ! It's really great thanks !!!! When would it be available on pypi?

**Comment by sebastiandres** [comment]
Excellent! I'll work on documentation and stuff so it's clearer how to use all this new features. For sure, the graphs on the admin view could be improved!

Let me know if you need help and of course, I'd love to take a look at the final app.

**Comment by sebastiandres** [comment]
It's finally completed! I'm closing this issue. 

Check out the interactive examples!!!
Simple activities: https://share.streamlit.io/sebastiandres/stb_activities_demo_v070/main
Traditional pagination: https://share.streamlit.io/sebastiandres/stb_chapter_demo_v070/main
The new book format: https://share.streamlit.io/sebastiandres/stb_book_demo_v070/main

And also a HUGE update to the docs: https://streamlit-book.readthedocs.io](https://t.co/uamp3ZYGL3
I had a few laughs putting some fun jokes in there.

**Comment by martinagalletti** [comment]
Perfect thanks a lot and great work!
