### ISSUE TITLE
how to how do i make the slider value stay the same even when moving pages?

### ISSUE THREAD

**Issue by riyosan** [sebastiandres/streamlit_book#3]
how do i make the slider value stay the same even when moving pages? when i move the slider value to 45 and go to next page or previous page and when i go back to that slider page the slider value stays 45, whether to implement session_state?

**Comment by sebastiandres** [comment]
Hi riyosan. It depends a bit on what you are trying to achieve. I think you could get away with a simple sidebar with a slider (easy and no session_state), or, if you need the slider on the actual page, you would need to have a different slider but initialize it with a value stored on the session_state.

I´d be glad to help, share your github repo and I´ll take a look.

**Comment by riyosan** [comment]
thank you for responding sir, this is [my github repo](https://github.com/riyosan/multiapp.git) I have 3 pages whose files I put in the 'apps' folder and those pages are preprocess, train_test, and predict. When I have set the slider value on the train_test page, the slider value will be reset when I go to the preprocess or predict page and back again to the train_test page, please help how can I not reset the slider value when I switch pages?

**Comment by sebastiandres** [comment]
Hi, I made a small example mixing data from sidebar and the page. I would advice playing around with this and add the variables you need, before doing complex/time consuming calculations.
App: https://share.streamlit.io/sebastiandres/stb_riyosan_example/main
Code: https://github.com/sebastiandres/stb_riyosan_example

Hope this helps! Let me know if you need anything else.

**Comment by riyosan** [comment]
thanks for shared sir, what is the use of the command
save answers = False and save answers=save answers, I don't understand, and I didn't succeed in applying it to my multipage

**Comment by sebastiandres** [comment]
It's an optional parameter, it can be safely ignored.
Take a look at the documentation: https://streamlit-book.readthedocs.io/en/latest/

**Comment by riyosan** [comment]
thans sir, but i have another problem sir i made 
_streamlit_app.py_
`import streamlit as st`
`import streamlit_book as stb`

`split_size = st.sidebar.slider('Rasio Pembagian Data (% Untuk Data Latih)', 10, 90, 80, 5)`
`st.session_state.split_size = split_size`

`dataset = st.sidebar.file_uploader("Unggah File CSV", type=['csv'])`
`st.session_state.dataset = dataset`

`stb.set_chapter_config(path="pages/")`

and in pages folder i have
_app_1.py_
`import pandas as pd`
`dataset = st.session_state.dataset`
`def load_datasets(dataset):`
	`df = pd.read_csv(dataset)`
	`return df`
`if dataset is not None:`
	`df=load_datasets(dataset)`
	`st.write(df)`
if I use the function in app_1.py it will show an error
> NameError: name 'pd' is not defined

i use file_uploader `dataset = st.sidebar.file_uploader("Unggah File CSV", type=['csv'])` to upload csv file and then i use function load_datasets to load the csv file

**Comment by riyosan** [comment]
is it not possible to use the function in a file in the pages folder?

**Comment by sebastiandres** [comment]
Hi, 

   That's weird, I never had that issue before. But it's true that the imported library does not seems to be available to function scope. You can get away with some alternatives, some as simple as the following:

```
if "dataset" in st.session_state:
    dataset = st.session_state.dataset
else:
    dataset = None

def load_datasets(dataset):
    import pandas as pd
    df = pd.read_csv(dataset)
    return df

if dataset is not None:
    df = load_datasets(dataset)
    st.write(df)
```
(Not the cleanest way, I agree)

Otherwise, and perhaps why I haven't had this issue before, is because I usually put all my helper funcions into a helpers.py, and import the functions when I need them. It's more clean, IMHO. 

Anyway, I'll take a look, but does not seems like an easy fix (there's quite some hacking under the hood to load the python files and pass them to streamlit on-the-fly). That's why "st.code" does not work.

In any case, please feel free to reach through twitter (@sebastiandres) or discord, and move help/advice on code over there.
