### ISSUE TITLE
Cannot define function in pages

### ISSUE THREAD

**Issue by noviechiuman** [sebastiandres/streamlit_book#7]
I have created a repository which follows this repo's structure: https://github.com/sebastiandres/stbook_multipaging

However, in the page .py file (e.g. https://github.com/sebastiandres/stbook_multipaging/blob/main/pages/02_book/multiple_choice/00_multiple_choice.py), I cannot define functions. Every time I define a function, it always return this error:
```NameError: name 'name' is not defined```

E.g. if inside my function there's a `df = pd.DataFrame()`, it'll return `NameError: name 'pd' is not defined` even though pandas has been declared.

If I move the page to the parent folder, the page loads and works fine. I kinda need the function for the st.cache_data() decorator tbh. Any solution to this?

**Comment by sebastiandres** [comment]
Yes, I'm having the same issue. I'd love to know a proper solution :C

It's a very bad solution, but you can add imports inside the functions as a workaround. 

```
def my_function():
   import pandas as pd
   # the rest of my code
```

**Comment by noviechiuman** [comment]
What I can think of is to create a .py file for your functions, then import them to the desired page. However, this means you cannot use the st.cache_data() decorator :(

Thanks for the workaround though!

**Comment by sebastiandres** [comment]
Thanks to @chrda81 's PR defining and using functions is now possible! Thanks @chrda81 !
