### ISSUE TITLE
Readthedocs goes 400

### ISSUE THREAD

**Issue by houfu** [sebastiandres/streamlit_book#8]
I just tried to visit https://streamlit_book.readthedocs.io/

Got a Bad Request (400) instead...

Will read the docs from the Github Repo instead then.

**Comment by sebastiandres** [comment]
Hi! The correct link is https://streamlit-book.readthedocs.io/en/latest/ ( so `-` instead of `_` ). 
If you find a link I miss typed, let me know to correct it! Thanks!
